### ISSUE TITLE
Windows documentation omits Redis installation step.

### ISSUE THREAD

**Issue by deathInTheAfternoon** [Fixel-Institute/BRAVO#9]
I noticed the [WSL2 installation instructions](https://bravo-documentation.jcagle.solutions/installation#windows-step-0-environment-setup) miss the following line used by previous the Linux install steps:
```
# Setup Redis Server on Docker for Django Channels
sudo docker run -p 6379:6379 -d redis:5
```
I'm assuming Django Channels wont work on WSL2 without the above step.

**Comment by JCagle95** [comment]
Thank you so much for the feedback. This is my mistake. I was originally doing Redis directly through Docker Desktop which is why I removed that command initially (but then I forgot to add it in installation procedure). The documentation page is now updated. 

Reference: 8f8d9692390b414670ede72e42dd289e24c5f6d6
